import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@workspace/api-client-react': path.resolve(__dirname, '../../lib/api-client-react/src/index.ts'),
      '@workspace/db': path.resolve(__dirname, '../../lib/db/src/index.ts'),
      '@workspace/api-zod': path.resolve(__dirname, '../../lib/api-zod/src/index.ts'),
      '@tanstack/react-query': path.resolve(__dirname, './node_modules/@tanstack/react-query'),
    },
    preserveSymlinks: true,
    mainFields: ['module', 'main'],
    dedupe: ['@tanstack/react-query', 'react', 'react-dom'],
  },
  optimizeDeps: {
    include: [
      'wouter',
      'regexparam',
      '@tanstack/react-query',
      '@tanstack/query-core',
      'use-sync-external-store',
      'react',
      'react-dom',
      'recharts',
      'lucide-react',
      'date-fns',
      'clsx',
      'tailwind-merge',
      'goober',
      'react-hot-toast',
      '@radix-ui/react-accordion',
      '@radix-ui/react-alert-dialog',
      '@radix-ui/react-aspect-ratio',
      '@radix-ui/react-avatar',
      '@radix-ui/react-checkbox',
      '@radix-ui/react-collapsible',
      '@radix-ui/react-context-menu',
      '@radix-ui/react-dialog',
      '@radix-ui/react-dropdown-menu',
      '@radix-ui/react-hover-card',
      '@radix-ui/react-label',
      '@radix-ui/react-menubar',
      '@radix-ui/react-navigation-menu',
      '@radix-ui/react-popover',
      '@radix-ui/react-progress',
      '@radix-ui/react-radio-group',
      '@radix-ui/react-scroll-area',
      '@radix-ui/react-select',
      '@radix-ui/react-separator',
      '@radix-ui/react-slider',
      '@radix-ui/react-slot',
      '@radix-ui/react-switch',
      '@radix-ui/react-tabs',
      '@radix-ui/react-toast',
      '@radix-ui/react-toggle',
      '@radix-ui/react-toggle-group',
      '@radix-ui/react-tooltip',
    ],
    esbuildOptions: {
      mainFields: ['module', 'main'],
    },
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    commonjsOptions: {
      transformMixedEsModules: true,
      include: [/node_modules/],
    },
    rollupOptions: {},
  },
  server: {
    host: '0.0.0.0',
    port: 5173,
  },
})
