import express from "express";
import cors from "cors";
import helmet from "helmet";
import dotenv from "dotenv";
import authRouter from "./routes/auth.js";
import usersRouter from "./routes/users.js";
import healthRouter from "./routes/health.js";
import { sessionsRouter } from "./routes/sessions.js";
import { logsRouter } from "./routes/logs.js";
import { correlationsRouter } from "./routes/correlations.js";
import { analyzeRouter } from "./routes/analyze.js";
import { reportsRouter } from "./routes/reports.js";
import { dashboardRouter } from "./routes/dashboard.js";
import { dailySummaryRouter } from "./routes/dailySummary.js";
import { n8nConfigRouter } from "./routes/n8nConfig.js";
import { connectorsRouter } from "./routes/connectors.js";
import { wazuhRouter } from "./routes/wazuh.js";
import { generalLimiter, authLimiter, logIngestionLimiter } from "./middlewares/rateLimiter.js";
import { logger } from "./lib/logger.js";

dotenv.config();
const app = express();
const trustProxy = process.env.TRUST_PROXY;
if (trustProxy) app.set("trust proxy", trustProxy === "1" ? 1 : trustProxy);
const PORT = process.env.PORT || 5000;
app.use(helmet({ crossOriginResourcePolicy: { policy: "same-site" }, contentSecurityPolicy: false }));
const allowedOrigin = process.env.ALLOWED_ORIGIN;
app.use(cors({ origin: allowedOrigin ? allowedOrigin : true, credentials: true, methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"], allowedHeaders: ["Content-Type", "Authorization"] }));
app.use(express.json({ limit: "5mb" }));
app.use(express.urlencoded({ extended: true, limit: "5mb" }));
app.use("/api/auth", authLimiter, authRouter);
app.use("/api/users", usersRouter);
app.use("/api/health", healthRouter);
app.get("/api/healthz", (_req, res) => res.json({ status: "ok", timestamp: new Date().toISOString() }));
app.use("/api", generalLimiter);
app.use("/api/wazuh", wazuhRouter);
app.use("/api/sessions", sessionsRouter);
app.use("/api/sessions", logIngestionLimiter, logsRouter);
app.use("/api/sessions", correlationsRouter);
app.use("/api/sessions", analyzeRouter);
app.use("/api/reports", reportsRouter);
app.use("/api/dashboard", dashboardRouter);
app.use("/api/daily-summary", dailySummaryRouter);
app.use("/api/n8n-config", n8nConfigRouter);
app.use("/api/connectors", connectorsRouter);
app.use((_req, res) => res.status(404).json({ error: "Not found" }));
app.listen(PORT, () => logger.info({ port: PORT }, "SOC Triage API server started"));
